# Generated by Django 5.0 on 2024-06-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('vid', models.FileField(blank=True, null=True, upload_to='pics/')),
                ('kin1', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('kin2', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('kin3', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('kin4', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('kin5', models.ImageField(blank=True, null=True, upload_to='pics/')),
            ],
        ),
    ]
