# Generated by Django 5.0 on 2024-06-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movenet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='x_vals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
